fn main() -> Result<(), String> {
    return Err("oops".into());
}
